LibStoga: ls::AbstractOdom Class Reference
ls::AbstractOdom Class Reference abstract
Abstract base class for all odometry implementations.
#include <odom.h>
Public Member Functions
virtual void initialize (std::initializer_list< uint8_t > ports)=0
Initialize odometry system with sensor ports.
virtual void compute ()
Update robot position based on sensor readings.
virtual double getX ()
Get current X coordinate.
virtual double getY ()
Get current Y coordinate.
virtual double getAngle ()
Get current heading angle.
virtual Position getPosition ()
Get complete current position.
virtual void resetX ()
Reset X coordinate to zero.
virtual void resetY ()
Reset Y coordinate to zero.
virtual void resetAngle ()
Reset heading angle to zero.
virtual void resetAll ()
Reset all position and heading to zero.
virtual double getDeltaX ()=0
Get X position change since last compute() call.
virtual double getDeltaY ()=0
Get Y position change since last compute() call.
virtual Angle getDeltaAngle ()=0
Get heading change since last compute() call.
virtual ~AbstractOdom ()=default
Virtual destructor for proper cleanup.
Protected Member Functions
AbstractOdom ()
Protected constructor for derived classes.
Protected Attributes
Position pos
Position prev_pos
Detailed Description
Abstract base class for all odometry implementations.
Defines the common interface for all odometry systems in the framework. Concrete implementations must provide position tracking capabilities using different sensor configurations (wheels, IMU, etc.).
This abstraction allows users to switch between different odometry implementations without changing their application code.
Definition at line 149 of file odom.h.
Constructor & Destructor Documentation
AbstractOdom()
ls::AbstractOdom::AbstractOdom () inline explicit protected
Protected constructor for derived classes.
Definition at line 157 of file odom.h.
References pos.
~AbstractOdom()
virtual ls::AbstractOdom::~AbstractOdom () virtual default
Virtual destructor for proper cleanup.
Member Function Documentation
compute()
void ls::AbstractOdom::compute () virtual
Update robot position based on sensor readings.
Computes new position and heading based on sensor data since last update. This method should be called regularly (typically in a control loop) to maintain accurate position tracking.
Exceptions
std::bad_function_call if not properly initialized
Reimplemented in ls::ImuOdom, ls::MCLTracker, and ls::ThreeWheelOdom.
Definition at line 10 of file odom.cpp.
References getDeltaAngle(), getDeltaX(), getDeltaY(), and pos.
getAngle()
double ls::AbstractOdom::getAngle () virtual
Get current heading angle.
Returns
Heading angle in degrees (bearing system: 0° = North)
Exceptions
std::bad_function_call if not properly initialized
Definition at line 28 of file odom.cpp.
References pos.
getDeltaAngle()
virtual Angle ls::AbstractOdom::getDeltaAngle () pure virtual
Get heading change since last compute() call.
Returns the incremental change in heading without resetting. Returns 0 on first call.
Returns
Delta angle in degrees
Exceptions
std::bad_function_call if not properly initialized
Implemented in ls::ImuOdom, ls::MCLTracker, and ls::ThreeWheelOdom.
Referenced by compute().
getDeltaX()
virtual double ls::AbstractOdom::getDeltaX () pure virtual
Get X position change since last compute() call.
Returns the incremental change in X position without resetting. Returns 0 on first call.
Returns
Delta X in inches
Exceptions
std::bad_function_call if not properly initialized
Implemented in ls::ImuOdom, ls::MCLTracker, and ls::ThreeWheelOdom.
Referenced by compute().
getDeltaY()
virtual double ls::AbstractOdom::getDeltaY () pure virtual
Get Y position change since last compute() call.
Returns the incremental change in Y position without resetting. Returns 0 on first call.
Returns
Delta Y in inches
Exceptions
std::bad_function_call if not properly initialized
Implemented in ls::ImuOdom, ls::MCLTracker, and ls::ThreeWheelOdom.
Referenced by compute().
getPosition()
Position ls::AbstractOdom::getPosition () virtual
Get complete current position.
Returns
Position structure with X, Y, and heading
Definition at line 33 of file odom.cpp.
References pos.
getX()
double ls::AbstractOdom::getX () virtual
Get current X coordinate.
Returns
X coordinate in inches from origin
Exceptions
std::bad_function_call if not properly initialized
Definition at line 18 of file odom.cpp.
References pos.
getY()
double ls::AbstractOdom::getY () virtual
Get current Y coordinate.
Returns
Y coordinate in inches from origin
Exceptions
std::bad_function_call if not properly initialized
Definition at line 23 of file odom.cpp.
References pos.
initialize()
virtual void ls::AbstractOdom::initialize (std::initializer_list< uint8_t > ports) pure virtual
Initialize odometry system with sensor ports.
Sets up the odometry system with the specified sensor ports. The exact meaning and order of ports depends on the concrete implementation:
ThreeWheelOdom: right, left, back tracking wheel ports
ImuOdom: horizontal, vertical tracking wheel ports, IMU port
Negative port numbers indicate reversed sensor mounting.
Parameters
ports List of sensor ports to initialize
Implemented in ls::ImuOdom, ls::MCLTracker, and ls::ThreeWheelOdom.
resetAll()
void ls::AbstractOdom::resetAll () virtual
Reset all position and heading to zero.
Resets robot to origin (0, 0) with 0° heading.
Reimplemented in ls::ImuOdom.
Definition at line 53 of file odom.cpp.
References resetAngle(), resetX(), and resetY().
Referenced by ls::ImuOdom::resetAll().
resetAngle()
void ls::AbstractOdom::resetAngle () virtual
Reset heading angle to zero.
Sets current heading to 0°, maintaining X and Y position.
Definition at line 48 of file odom.cpp.
References pos.
Referenced by resetAll().
resetX()
void ls::AbstractOdom::resetX () virtual
Reset X coordinate to zero.
Sets current X position to 0, maintaining Y and heading.
Definition at line 38 of file odom.cpp.
References pos.
Referenced by resetAll().
resetY()
void ls::AbstractOdom::resetY () virtual
Reset Y coordinate to zero.
Sets current Y position to 0, maintaining X and heading.
Definition at line 43 of file odom.cpp.
References pos.
Referenced by resetAll().
Member Data Documentation
pos
Position ls::AbstractOdom::pos protected
Current robot position and heading
Definition at line 151 of file odom.h.
Referenced by AbstractOdom(), compute(), ls::ImuOdom::compute(), ls::ThreeWheelOdom::compute(), getAngle(), getPosition(), getX(), getY(), resetAngle(), resetX(), resetY(), and ls::MCLTracker::updateEstimate().
prev_pos
Position ls::AbstractOdom::prev_pos protected
Previous position for delta calculations
Definition at line 152 of file odom.h.
The documentation for this class was generated from the following files:
include/LibStoga/odom.h
src/LibStoga/odom.cpp