LibStoga: ls::DriverControl Class Reference
ls::DriverControl Class Reference
Enhanced driver control system with multiple drive modes.
#include <driver_control.h>
Classes
struct DriveConfig
Configuration structure for driver control settings.
Public Types
enum DriveType {
ARCADE , TANK , CHEESY , CURVATURE ,
GTA
}
Available drive control modes.
Public Member Functions
DriverControl ()
Default constructor with standard configuration.
DriverControl (const DriveConfig &config)
Constructor with custom configuration.
void setConfig (const DriveConfig &config)
Update drive configuration at runtime.
const DriveConfig & getConfig () const
Get current drive configuration.
void calculateDrivePowers (pros::Controller &controller, double &leftMotor, double &rightMotor)
Calculate motor powers from controller input.
Private Member Functions
double applyCurveToInput (double input, JoystickCurve::CurveType curveType, double gain)
Apply curve and deadzone to input value.
Static Private Member Functions
static DriveConfig getDefaultConfig ()
Get default drive configuration.
Private Attributes
DriveConfig config_
Detailed Description
Enhanced driver control system with multiple drive modes.
The DriverControl class provides a complete driver control solution with support for multiple drive modes, configurable joystick curves, and real-time parameter adjustment. It integrates seamlessly with PROS controllers and provides optimized motor power calculations.
Drive Mode Details:
Arcade: Traditional single-stick driving (throttle + turn)
Tank: Independent left/right stick control
Cheesy Drive: Enhanced arcade with quick-turn capability
Curvature: Radius-based turning for smooth curved paths
GTA: Trigger-based acceleration with analog steering
Configuration Example:
DriverControl::DriveConfig config;
config.type = DriverControl::CHEESY;
config.throttleCurve = JoystickCurve::EXPONENTIAL;
config.turnCurve = JoystickCurve::SIGMOID;
config.throttleGain = 1.2;
config.turnGain = 0.8;
DriverControl driver(config);
// In driver control loop
double leftPower, rightPower;
driver.calculateDrivePowers(controller, leftPower, rightPower);
leftMotors.move(leftPower);
rightMotors.move(rightPower);
Definition at line 233 of file driver_control.h.
Member Enumeration Documentation
DriveType
enum ls::DriverControl::DriveType
Available drive control modes.
Enumerator
ARCADE
Single stick: throttle + turn
TANK
Dual stick: independent left/right control
CHEESY
Cheesy Drive: throttle + quick turn boost
CURVATURE
Curvature drive: throttle + radius control
GTA
GTA-style: trigger acceleration + analog steering
Definition at line 238 of file driver_control.h.
Constructor & Destructor Documentation
DriverControl() [1/2]
ls::DriverControl::DriverControl () inline
Default constructor with standard configuration.
Definition at line 262 of file driver_control.h.
References config_, and getDefaultConfig().
DriverControl() [2/2]
ls::DriverControl::DriverControl (const DriveConfig & config) inline
Constructor with custom configuration.
Parameters
config Drive configuration settings
Definition at line 269 of file driver_control.h.
References config_.
Member Function Documentation
applyCurveToInput()
double ls::DriverControl::applyCurveToInput (double input, JoystickCurve::CurveType curveType, double gain) inline private
Apply curve and deadzone to input value.
Parameters
input Raw input value
curveType Curve type to apply
gain Curve gain factor
Returns
Processed output value
Definition at line 419 of file driver_control.h.
References ls::JoystickCurve::applyCurve(), and config_.
Referenced by calculateDrivePowers().
calculateDrivePowers()
void ls::DriverControl::calculateDrivePowers (pros::Controller & controller, double & leftMotor, double & rightMotor) inline
Calculate motor powers from controller input.
Processes controller input according to the current drive configuration and calculates appropriate motor powers for left and right drive motors. All curves, deadzones, and drive mode logic are applied automatically.
Parameters
controller PROS controller reference
leftMotor Output power for left motors (-127 to 127)
rightMotor Output power for right motors (-127 to 127)
Note
Motor powers are automatically clamped to valid range
Definition at line 305 of file driver_control.h.
References applyCurveToInput(), ARCADE, CHEESY, config_, CURVATURE, GTA, and TANK.
getConfig()
const DriveConfig & ls::DriverControl::getConfig () const inline
Get current drive configuration.
Returns
Current drive configuration settings
Definition at line 288 of file driver_control.h.
References config_.
getDefaultConfig()
DriveConfig ls::DriverControl::getDefaultConfig () inline static private
Get default drive configuration.
Returns
Default configuration with sensible defaults
Definition at line 399 of file driver_control.h.
References ARCADE, ls::DriverControl::DriveConfig::deadzoneThreshold, ls::DriverControl::DriveConfig::enableDeadzone, ls::JoystickCurve::EXPONENTIAL, ls::JoystickCurve::SIGMOID, ls::DriverControl::DriveConfig::throttleCurve, ls::DriverControl::DriveConfig::throttleGain, ls::DriverControl::DriveConfig::turnCurve, ls::DriverControl::DriveConfig::turnGain, and ls::DriverControl::DriveConfig::type.
Referenced by DriverControl().
setConfig()
void ls::DriverControl::setConfig (const DriveConfig & config) inline
Update drive configuration at runtime.
Allows changing drive settings during operation, useful for driver preference adjustments or mode switching.
Parameters
config New drive configuration
Definition at line 279 of file driver_control.h.
References config_.
Member Data Documentation
config_
DriveConfig ls::DriverControl::config_ private
Current drive configuration
Definition at line 392 of file driver_control.h.
Referenced by applyCurveToInput(), calculateDrivePowers(), DriverControl(), DriverControl(), getConfig(), and setConfig().
The documentation for this class was generated from the following file:
include/LibStoga/driver_control.h