LibStoga: ls::PurePursuit Class Reference
ls::PurePursuit Class Reference
Pure Pursuit path following controller.
#include <pure_pursuit.h>
Public Member Functions
PurePursuit (AbstractOdom &tracker, double lookahead, double kTurn=1.0)
Construct Pure Pursuit controller.
void setPath (const Path &p)
Set the path to follow.
void setLookahead (double l)
Set the lookahead distance.
PursuitOutput update ()
Update controller and get motion commands.
bool isFinished () const
Check if path following is complete.
Private Member Functions
std::optional< Point > findLookahead (const Pose &robot)
Find the lookahead point on the path.
Private Attributes
AbstractOdom & odom
Path path
size_t currentIdx {0}
double lookaheadDist
double kTurn
bool finished {false}
Detailed Description
Pure Pursuit path following controller.
Implements the Pure Pursuit algorithm for smooth autonomous path following. The controller takes a series of waypoints and generates velocity commands to guide the robot along the desired path.
The algorithm works by:
Finding a "lookahead point" on the path ahead of the robot
Calculating the curvature needed to reach that point
Generating proportional control outputs to minimize error
Usage Example:
// Create odometry system
ThreeWheelOdom odom(centerToRight, centerToLeft, centerToBack);
odom.initialize({1, 2, 3});
// Create Pure Pursuit controller
PurePursuit controller(odom, 12.0); // 12 inch lookahead
// Set path waypoints
Path waypoints = {{0, 0}, {24, 0}, {24, 24}, {0, 24}};
controller.setPath(waypoints);
// In control loop
while (!controller.isFinished()) {
    PursuitOutput output = controller.update();
    chassis.arcade(output.linear, output.angular);
    pros::delay(20);
}
Definition at line 83 of file pure_pursuit.h.
Constructor & Destructor Documentation
PurePursuit()
ls::PurePursuit::PurePursuit (AbstractOdom & tracker, double lookahead, double kTurn = 1.0) explicit
Construct Pure Pursuit controller.
Creates a new Pure Pursuit controller with the specified odometry system and lookahead distance.
Parameters
tracker Reference to odometry system for position feedback
lookahead Lookahead distance in inches (typically 6-18 inches)
kTurn Curvature gain multiplier (default: 1.0)
References kTurn.
Member Function Documentation
findLookahead()
std::optional< Point > ls::PurePursuit::findLookahead (const Pose & robot) private
Find the lookahead point on the path.
Searches the path to find the point that is exactly the lookahead distance ahead of the robot's current position. This point becomes the target for curvature calculations.
Parameters
robot Current robot pose (position + heading)
Returns
Lookahead point if found, std::nullopt if at path end
Definition at line 5 of file pure_pursuit.cpp.
References currentIdx, ls::distance(), lookaheadDist, and path.
Referenced by update().
isFinished()
bool ls::PurePursuit::isFinished () const inline
Check if path following is complete.
Returns
true if the robot has reached the end of the path
Definition at line 134 of file pure_pursuit.h.
References finished.
Referenced by ls::Chassis::followPath().
setLookahead()
void ls::PurePursuit::setLookahead (double l)
Set the lookahead distance.
Dynamically adjusts the lookahead distance during operation. Larger values provide smoother but less precise following. Smaller values provide more precise but potentially jerky following.
Parameters
l New lookahead distance in inches
setPath()
void ls::PurePursuit::setPath (const Path & p)
Set the path to follow.
Loads a new path for the controller to follow. The path should be a series of waypoints that define the desired robot trajectory.
Parameters
p Vector of waypoints defining the path
Referenced by ls::Chassis::followPath().
update()
PursuitOutput ls::PurePursuit::update ()
Update controller and get motion commands.
Calculates the current control outputs based on robot position and path following requirements. This should be called regularly in the control loop (typically 50Hz).
Returns
PursuitOutput containing linear/angular velocities and completion status
Definition at line 16 of file pure_pursuit.cpp.
References ls::PursuitOutput::angular, ls::degreesToRadians(), ls::distance(), ls::PursuitOutput::done, findLookahead(), finished, ls::Angle::getAngle(), ls::Pose::heading, kTurn, ls::PursuitOutput::linear, lookaheadDist, odom, path, ls::Point::x, and ls::Point::y.
Referenced by ls::Chassis::followPath().
Member Data Documentation
currentIdx
size_t ls::PurePursuit::currentIdx {0} private
Index of current segment in path
Definition at line 139 of file pure_pursuit.h.
Referenced by findLookahead().
finished
bool ls::PurePursuit::finished {false} private
Whether path following is complete
Definition at line 142 of file pure_pursuit.h.
Referenced by isFinished(), and update().
kTurn
double ls::PurePursuit::kTurn private
Curvature gain multiplier
Definition at line 141 of file pure_pursuit.h.
Referenced by PurePursuit(), and update().
lookaheadDist
double ls::PurePursuit::lookaheadDist private
Lookahead distance in inches
Definition at line 140 of file pure_pursuit.h.
Referenced by findLookahead(), and update().
odom
AbstractOdom& ls::PurePursuit::odom private
Reference to odometry system for position feedback
Definition at line 137 of file pure_pursuit.h.
Referenced by update().
path
Path ls::PurePursuit::path private
Current path being followed
Definition at line 138 of file pure_pursuit.h.
Referenced by findLookahead(), and update().
The documentation for this class was generated from the following files:
include/LibStoga/pure_pursuit.h
src/LibStoga/pure_pursuit.cpp