LibStoga: ls::JoystickCurve Class Reference
ls::JoystickCurve Class Reference
Joystick curve utilities for enhanced driver control.
#include <driver_control.h>
Public Types
enum CurveType {
LINEAR , EXPONENTIAL , SIGMOID , CUBIC ,
CHEESY_DRIVE
}
Available joystick curve types.
Static Public Member Functions
static double applyCurve (double input, CurveType type, double gain=1.0)
Apply a curve transformation to joystick input.
static double expoCurve (double input, double gain)
Apply exponential curve for fine low-speed control.
static double sigmoidCurve (double input, double gain)
Apply sigmoid curve for smooth S-curve acceleration.
static double cubicCurve (double input, double gain)
Apply cubic curve for aggressive low-speed control.
static double cheesyCurve (double input, double gain)
Cheesy Drive optimized curve.
Detailed Description
Joystick curve utilities for enhanced driver control.
The JoystickCurve class provides mathematical transformations to modify controller input for better driver feel and precision. Different curve types optimize control for various driving scenarios and driver preferences.
Curve Types and Use Cases:
Linear: Best for precise, predictable control (good for beginners)
Exponential: Excellent for fine low-speed control with high-speed capability
Sigmoid: Natural acceleration feel, smooth throughout range
Cubic: Maximum precision at low speeds (advanced drivers)
Cheesy Drive: Optimized for quick turns and smooth driving
Usage Example:
// Apply exponential curve to throttle input
double rawThrottle = controller.get_analog(pros::E_CONTROLLER_ANALOG_LEFT_Y);
double curvedThrottle = JoystickCurve::applyCurve(rawThrottle,
                                                  JoystickCurve::EXPONENTIAL,
                                                  1.5); // Aggressive curve
Definition at line 68 of file driver_control.h.
Member Enumeration Documentation
CurveType
enum ls::JoystickCurve::CurveType
Available joystick curve types.
Enumerator
LINEAR
No curve, direct 1:1 mapping
EXPONENTIAL
Exponential curve for fine low-speed control
SIGMOID
S-curve for smooth, natural acceleration
CUBIC
Cubic curve for maximum low-speed precision
CHEESY_DRIVE
Special curve optimized for Cheesy Drive mode
Definition at line 73 of file driver_control.h.
Member Function Documentation
applyCurve()
double ls::JoystickCurve::applyCurve (double input, CurveType type, double gain = 1.0) inline static
Apply a curve transformation to joystick input.
Transforms raw joystick input using the specified curve type and gain. All curves include automatic deadzone handling to prevent jitter.
Parameters
input Raw joystick input (-127 to 127)
type Type of curve to apply
gain Curve intensity multiplier (0.0 = linear, higher = more aggressive)
Returns
Curved output value (-127 to 127)
Note
Input is automatically clamped and includes 5% deadzone by default
Definition at line 94 of file driver_control.h.
References CHEESY_DRIVE, cheesyCurve(), CUBIC, cubicCurve(), expoCurve(), EXPONENTIAL, LINEAR, SIGMOID, and sigmoidCurve().
Referenced by ls::DriverControl::applyCurveToInput().
cheesyCurve()
double ls::JoystickCurve::cheesyCurve (double input, double gain) inline static
Cheesy Drive optimized curve.
Special curve designed specifically for Cheesy Drive mode, blending cubic precision at low speeds with linear response at high speeds for optimal driving feel.
Parameters
input Normalized input (-1.0 to 1.0)
gain Curve blend factor (higher = more linear at high speeds)
Returns
Curved output (-1.0 to 1.0)
Definition at line 190 of file driver_control.h.
Referenced by applyCurve().
cubicCurve()
double ls::JoystickCurve::cubicCurve (double input, double gain) inline static
Apply cubic curve for aggressive low-speed control.
Provides maximum precision at low speeds by cubing the input, making small joystick movements produce very small outputs. Best for advanced drivers who need fine control.
Parameters
input Normalized input (-1.0 to 1.0)
gain Additional linear component (higher = less aggressive)
Returns
Curved output (-1.0 to 1.0)
Definition at line 173 of file driver_control.h.
Referenced by applyCurve().
expoCurve()
double ls::JoystickCurve::expoCurve (double input, double gain) inline static
Apply exponential curve for fine low-speed control.
Creates a curve where small inputs produce even smaller outputs, allowing for precise control at low speeds while maintaining full power capability at high speeds.
Parameters
input Normalized input (-1.0 to 1.0)
gain Curve aggressiveness (higher = more pronounced curve)
Returns
Curved output (-1.0 to 1.0)
Definition at line 142 of file driver_control.h.
Referenced by applyCurve().
sigmoidCurve()
double ls::JoystickCurve::sigmoidCurve (double input, double gain) inline static
Apply sigmoid curve for smooth S-curve acceleration.
Creates a smooth S-shaped curve that provides natural acceleration feel, with gradual changes at low speeds and more responsive changes at higher speeds.
Parameters
input Normalized input (-1.0 to 1.0)
gain Curve steepness (higher = steeper S-curve)
Returns
Curved output (-1.0 to 1.0)
Definition at line 157 of file driver_control.h.
Referenced by applyCurve().
The documentation for this class was generated from the following file:
include/LibStoga/driver_control.h