LibStoga: ls::SystemHealthMonitor Class Reference
ls::SystemHealthMonitor Class Reference
Comprehensive system health monitoring and diagnostics.
#include <system_health.h>
Classes
struct HealthIssue
Detailed information about a specific health issue.
struct MotorHealth
Health information for a single motor.
struct SystemMetrics
Complete system health metrics snapshot.
Public Types
enum HealthStatus { HEALTHY , WARNING , CRITICAL , FAILURE }
Overall system health status levels.
enum IssueType {
TUG_OF_WAR , BROWNOUT , BROKEN_DRIVE , STALL ,
OVERCURRENT , TEMPERATURE , ODOMETRY_DRIFT , SENSOR_FAILURE
}
Types of health issues that can be detected.
Public Member Functions
SystemHealthMonitor ()
Default constructor.
~SystemHealthMonitor ()
Destructor - stops monitoring task.
void setEnabled (bool enabled)
Enable or disable health monitoring.
void startMonitoring ()
Start background monitoring task.
void stopMonitoring ()
Stop monitoring task.
HealthStatus getOverallHealth () const
Get current overall system health status.
std::vector< HealthIssue > getIssues () const
Get list of current health issues.
SystemMetrics getMetrics () const
Get current system metrics.
void registerMotor (int port, pros::Motor *motor)
Register a motor for health monitoring.
void setHealthCallback (std::function< void(HealthStatus, const std::vector< HealthIssue > &)> callback)
Set callback for health status changes.
void forceHealthCheck ()
Manually trigger a health check.
void clearResolvedIssues ()
Clear resolved health issues.
Private Member Functions
void updateMetrics ()
Update all system health metrics.
void checkForIssues ()
Check for health issues based on current metrics.
Private Attributes
bool enabled_
pros::Task * monitoringTask_
SystemMetrics currentMetrics_
std::vector< HealthIssue > issues_
std::vector< std::pair< int, pros::Motor * > > monitoredMotors_
std::function< void(HealthStatus, const std::vector< HealthIssue > &)> healthCallback_
std::deque< double > voltageHistory_
std::deque< double > currentHistory_
std::deque< double > positionHistory_
Detailed Description
Comprehensive system health monitoring and diagnostics.
The SystemHealthMonitor provides real-time monitoring of all critical robot systems, detecting issues before they cause failures. It runs as a background task and provides both programmatic access to health data and callback-based notifications for critical issues.
The monitor tracks:
Motor health (current, temperature, RPM, stall conditions)
Battery status (voltage, current, brownout detection)
System performance trends
Odometry drift detection
Sensor communication failures
Usage Example:
// Get global health monitor
auto& health = getHealthMonitor();
// Register motors for monitoring
health.registerMotor(1, &leftFrontMotor);
health.registerMotor(2, &leftBackMotor);
health.registerMotor(3, &rightFrontMotor);
health.registerMotor(4, &rightBackMotor);
// Set up health callback
health.setHealthCallback([](SystemHealthMonitor::HealthStatus status,
                           const std::vector<SystemHealthMonitor::HealthIssue>& issues) {
    if (status >= SystemHealthMonitor::WARNING) {
        // Handle health issues
        pros::lcd::print(0, "Health Issue: %s", issues.back().description.c_str());
    }
});
// Start monitoring
health.startMonitoring();
// Check health in main loop
auto metrics = health.getMetrics();
if (metrics.batteryVoltage < 7.0) {
    // Low battery warning
}
Definition at line 90 of file system_health.h.
Member Enumeration Documentation
HealthStatus
enum ls::SystemHealthMonitor::HealthStatus
Overall system health status levels.
Enumerator
HEALTHY
All systems normal
WARNING
Minor issues detected, monitor closely
CRITICAL
Major issues requiring immediate attention
FAILURE
System failure, robot may be inoperable
Definition at line 95 of file system_health.h.
IssueType
enum ls::SystemHealthMonitor::IssueType
Types of health issues that can be detected.
Enumerator
TUG_OF_WAR
Robot being pushed or stalled externally
BROWNOUT
Low battery voltage detected
BROKEN_DRIVE
Drive motor failure or disconnection
STALL
Motor stall detection
OVERCURRENT
Motor drawing excessive current
TEMPERATURE
Motor overheating
ODOMETRY_DRIFT
Odometry position drift detected
SENSOR_FAILURE
Sensor communication failure
Definition at line 105 of file system_health.h.
Constructor & Destructor Documentation
SystemHealthMonitor()
ls::SystemHealthMonitor::SystemHealthMonitor ()
Default constructor.
Definition at line 6 of file system_health.cpp.
References enabled_, and monitoringTask_.
~SystemHealthMonitor()
ls::SystemHealthMonitor::~SystemHealthMonitor ()
Destructor - stops monitoring task.
Definition at line 8 of file system_health.cpp.
References stopMonitoring().
Member Function Documentation
checkForIssues()
void ls::SystemHealthMonitor::checkForIssues () private
Check for health issues based on current metrics.
Analyzes the current metrics against thresholds to detect potential problems and creates appropriate health issues.
Definition at line 91 of file system_health.cpp.
Referenced by forceHealthCheck().
clearResolvedIssues()
void ls::SystemHealthMonitor::clearResolvedIssues ()
Clear resolved health issues.
Removes health issues that are older than 30 seconds, assuming they have been resolved or are no longer relevant.
Definition at line 69 of file system_health.cpp.
Referenced by forceHealthCheck().
forceHealthCheck()
void ls::SystemHealthMonitor::forceHealthCheck ()
Manually trigger a health check.
Forces an immediate health check outside the normal monitoring cycle. Useful for one-time health assessments or debugging.
Definition at line 63 of file system_health.cpp.
References checkForIssues(), clearResolvedIssues(), and updateMetrics().
Referenced by startMonitoring().
getIssues()
std::vector< SystemHealthMonitor::HealthIssue > ls::SystemHealthMonitor::getIssues () const
Get list of current health issues.
Returns
Vector of all currently active health issues
Definition at line 47 of file system_health.cpp.
References issues_.
getMetrics()
SystemHealthMonitor::SystemMetrics ls::SystemHealthMonitor::getMetrics () const
Get current system metrics.
Returns
Complete snapshot of current system health metrics
Definition at line 51 of file system_health.cpp.
References currentMetrics_.
getOverallHealth()
SystemHealthMonitor::HealthStatus ls::SystemHealthMonitor::getOverallHealth () const
Get current overall system health status.
Returns
Current health status (HEALTHY, WARNING, CRITICAL, or FAILURE)
Definition at line 35 of file system_health.cpp.
References CRITICAL, FAILURE, HEALTHY, issues_, and WARNING.
registerMotor()
void ls::SystemHealthMonitor::registerMotor (int port, pros::Motor * motor)
Register a motor for health monitoring.
Adds a motor to the monitoring system. The motor will be checked for current draw, temperature, RPM, and stall conditions.
Parameters
port Motor port number
motor Pointer to PROS motor object
Definition at line 55 of file system_health.cpp.
References monitoredMotors_.
setEnabled()
void ls::SystemHealthMonitor::setEnabled (bool enabled)
Enable or disable health monitoring.
Parameters
enabled Whether to enable monitoring
Definition at line 12 of file system_health.cpp.
References enabled_.
setHealthCallback()
void ls::SystemHealthMonitor::setHealthCallback (std::function< void(HealthStatus, const std::vector< HealthIssue > &)> callback)
Set callback for health status changes.
Registers a callback function that will be called whenever the system health status changes or new issues are detected.
Parameters
callback Function to call on health changes
Definition at line 59 of file system_health.cpp.
References healthCallback_.
startMonitoring()
void ls::SystemHealthMonitor::startMonitoring ()
Start background monitoring task.
Begins continuous health monitoring in a separate PROS task. The task runs every 100ms checking all monitored systems.
Definition at line 16 of file system_health.cpp.
References enabled_, forceHealthCheck(), and monitoringTask_.
stopMonitoring()
void ls::SystemHealthMonitor::stopMonitoring ()
Stop monitoring task.
Stops the background monitoring task and cleans up resources.
Definition at line 27 of file system_health.cpp.
References enabled_, and monitoringTask_.
Referenced by ~SystemHealthMonitor().
updateMetrics()
void ls::SystemHealthMonitor::updateMetrics () private
Update all system health metrics.
Collects current data from all monitored systems including battery status, motor health, and sensor readings.
Definition at line 73 of file system_health.cpp.
References ls::SystemHealthMonitor::MotorHealth::current, currentMetrics_, ls::SystemHealthMonitor::MotorHealth::isStalled, ls::SystemHealthMonitor::MotorHealth::lastUpdate, monitoredMotors_, ls::SystemHealthMonitor::MotorHealth::port, ls::SystemHealthMonitor::MotorHealth::power, ls::SystemHealthMonitor::MotorHealth::rpm, and ls::SystemHealthMonitor::MotorHealth::temperature.
Referenced by forceHealthCheck().
Member Data Documentation
currentHistory_
std::deque<double> ls::SystemHealthMonitor::currentHistory_ private
Battery current history
Definition at line 251 of file system_health.h.
currentMetrics_
SystemMetrics ls::SystemHealthMonitor::currentMetrics_ private
Current health metrics
Definition at line 244 of file system_health.h.
Referenced by getMetrics(), and updateMetrics().
enabled_
bool ls::SystemHealthMonitor::enabled_ private
Whether monitoring is enabled
Definition at line 242 of file system_health.h.
Referenced by setEnabled(), startMonitoring(), stopMonitoring(), and SystemHealthMonitor().
healthCallback_
std::function<void(HealthStatus, const std::vector<HealthIssue>&)> ls::SystemHealthMonitor::healthCallback_ private
Health change callback
Definition at line 247 of file system_health.h.
Referenced by setHealthCallback().
issues_
std::vector<HealthIssue> ls::SystemHealthMonitor::issues_ private
List of active issues
Definition at line 245 of file system_health.h.
Referenced by getIssues(), and getOverallHealth().
monitoredMotors_
std::vector<std::pair<int, pros::Motor*> > ls::SystemHealthMonitor::monitoredMotors_ private
Motors being monitored
Definition at line 246 of file system_health.h.
Referenced by registerMotor(), and updateMetrics().
monitoringTask_
pros::Task* ls::SystemHealthMonitor::monitoringTask_ private
Background monitoring task
Definition at line 243 of file system_health.h.
Referenced by startMonitoring(), stopMonitoring(), and SystemHealthMonitor().
positionHistory_
std::deque<double> ls::SystemHealthMonitor::positionHistory_ private
Position history for drift detection
Definition at line 252 of file system_health.h.
voltageHistory_
std::deque<double> ls::SystemHealthMonitor::voltageHistory_ private
Battery voltage history
Definition at line 250 of file system_health.h.
The documentation for this class was generated from the following files:
include/LibStoga/system_health.h
src/LibStoga/system_health.cpp