LibStoga: ls::Chassis Class Reference
ls::Chassis Class Reference
Main chassis control class for robot movement.
#include <chassis.h>
Public Member Functions
void setController (pros::Controller &cont)
Set the controller for user input and cancellation.
pros::Controller * getController ()
Get the currently associated controller.
std::shared_ptr< ls::AbstractOdom > getOdom ()
Get access to the odometry system.
std::shared_ptr< AbstractPID > getLateralControl ()
Get the lateral motion PID controller.
std::shared_ptr< AbstractPID > getAngularControl ()
Get the angular motion PID controller.
std::vector< pros::Motor > & getLeftMotorVec ()
Get the left motor vector.
std::vector< pros::Motor > & getRightMotorVec ()
Get the right motor vector.
std::shared_ptr< pros::MotorGroup > getLeftMotors ()
Get the left motor group.
std::shared_ptr< pros::MotorGroup > getRightMotors ()
Get the right motor group.
bool isAdaptivePIDEnabled () const
Check if adaptive PID is enabled.
void updateAdaptivePID ()
Update adaptive PID controllers.
Chassis (std::vector< pros::Motor > _left_motors, std::vector< pros::Motor > _right_motors, std::shared_ptr< pros::MotorGroup > _right, std::shared_ptr< pros::MotorGroup > _left, std::shared_ptr< ls::AbstractOdom > _odom, std::shared_ptr< ls::AbstractPID > _lateral_control, std::shared_ptr< ls::AbstractPID > _angular_control, const ChassisConfig &cfg={})
Construct a new Chassis object.
Chassis (const Chassis &)=default
Chassis & operator= (const Chassis &)=default
Chassis (Chassis &&)=default
Chassis & operator= (Chassis &&)=default
void moveToPoint (double X, double Y, unsigned int timeout, bool reverse=false)
Move chassis to a specific point in Cartesian coordinates.
void turnToPoint (double X, double Y, unsigned int timeout, bool reverse=false)
Turn chassis to face a specific point.
double turnToAngle (double angle, unsigned int timeout)
Turn chassis to a specific absolute angle.
double driveRelative (double distance, unsigned int timeout)
Drive forward/backward a relative distance.
double turnRelative (double deltaAngle, unsigned int timeout)
Turn by a relative angle change.
void tank_drive (double left_y, double right_y)
Manual tank drive control.
void arcade (double forward, double turn)
Manual arcade drive control.
void followPath (const Path &path, double lookahead, unsigned int timeout)
Follow a path using pure pursuit algorithm.
Private Member Functions
double move_priority (Angle &angle) const
Calculate movement priority for coordinated motion.
Private Attributes
std::vector< pros::Motor > left_motors
std::vector< pros::Motor > right_motors
std::shared_ptr< pros::MotorGroup > right
std::shared_ptr< pros::MotorGroup > left
std::shared_ptr< ls::AbstractOdom > odom
std::shared_ptr< ls::AbstractPID > lateral_control
std::shared_ptr< ls::AbstractPID > angular_control
double turn_sensitivity
double threshold_lateral
double threshold_angular
unsigned int threshold_timeout
bool enable_cancel
pros::controller_digital_e_t cancel_button
bool enable_adaptive_pid
pros::Controller * controller
std::unique_ptr< AdaptivePIDController > lateral_adaptive_controller
std::unique_ptr< AdaptivePIDController > angular_adaptive_controller
Detailed Description
Main chassis control class for robot movement.
The Chassis class provides comprehensive control over robot movement including:
Manual control via tank or arcade drive
Autonomous motion primitives with PID control
Path following capabilities
Integrated odometry for position feedback
Adaptive PID tuning for optimal performance
The class currently supports tank drive configuration with left/right motor groups. Future versions may add support for other drive configurations (Mecanum, X-drive, etc.).
Note
All distances are in inches, angles in degrees (bearing system: 0° = North)
Warning
Requires proper motor calibration and PID tuning for optimal performance
Definition at line 73 of file chassis.h.
Constructor & Destructor Documentation
Chassis() [1/3]
ls::Chassis::Chassis (std::vector< pros::Motor > _left_motors, std::vector< pros::Motor > _right_motors, std::shared_ptr< pros::MotorGroup > _right, std::shared_ptr< pros::MotorGroup > _left, std::shared_ptr< ls::AbstractOdom > _odom, std::shared_ptr< ls::AbstractPID > _lateral_control, std::shared_ptr< ls::AbstractPID > _angular_control, const ChassisConfig & cfg = {}) explicit
Construct a new Chassis object.
Creates a chassis with the specified motor groups, odometry system, and PID controllers. Configuration can be customized via the config parameter.
Parameters
_left_motors Vector of left side motors
_right_motors Vector of right side motors
_right Shared pointer to right side motor group
_left Shared pointer to left side motor group
_odom Shared pointer to odometry system
_lateral_control Shared pointer to lateral PID controller
_angular_control Shared pointer to angular PID controller
cfg Configuration struct (uses defaults if not provided)
Definition at line 36 of file chassis.cpp.
References angular_adaptive_controller, angular_control, ls::ChassisConfig::angularThreshold, cancel_button, ls::ChassisConfig::cancelButton, controller, ls::ChassisConfig::dwellTimeMs, enable_adaptive_pid, enable_cancel, ls::ChassisConfig::enableAdaptivePID, ls::ChassisConfig::enableCancel, ls::PIDGains::kD, ls::PIDGains::kI, ls::PIDGains::kP, lateral_adaptive_controller, lateral_control, ls::ChassisConfig::lateralThreshold, left, left_motors, odom, right, right_motors, threshold_angular, threshold_lateral, threshold_timeout, turn_sensitivity, and ls::ChassisConfig::turnSensitivity.
Referenced by Chassis(), Chassis(), operator=(), and operator=().
Chassis() [2/3]
ls::Chassis::Chassis (const Chassis &) default
References Chassis().
Chassis() [3/3]
ls::Chassis::Chassis (Chassis &&) default
References Chassis().
Member Function Documentation
arcade()
void ls::Chassis::arcade (double forward, double turn)
Manual arcade drive control.
Controls the chassis using arcade drive logic with separate forward/backward and turn inputs. This provides more intuitive control for drivers.
Parameters
forward Forward/backward movement input (-1 to 1 or -127 to 127)
turn Left/right turn input (-1 to 1 or -127 to 127)
Definition at line 376 of file chassis.cpp.
driveRelative()
double ls::Chassis::driveRelative (double distance, unsigned int timeout)
Drive forward/backward a relative distance.
Moves the robot forward or backward by the specified distance from its current position using PID control.
Parameters
distance Distance to drive in inches (positive = forward, negative = backward)
timeout Maximum time to complete movement in milliseconds
Returns
Actual distance traveled when movement completed or timed out
Definition at line 271 of file chassis.cpp.
References cancel_button, ls::clampPower(), controller, DBG_PRINT, ls::distance(), enable_cancel, ls::Timer::isDone(), lateral_control, left, LOOP_DELAY, odom, right, threshold_lateral, and threshold_timeout.
followPath()
void ls::Chassis::followPath (const Path & path, double lookahead, unsigned int timeout)
Follow a path using pure pursuit algorithm.
Executes path following using the pure pursuit algorithm to smoothly navigate through a series of waypoints. The lookahead distance determines how far ahead on the path the robot aims.
Parameters
path Vector of waypoints defining the path
lookahead Lookahead distance in inches for path following
timeout Maximum time to complete path following in milliseconds
Definition at line 249 of file chassis.cpp.
References ls::clampPower(), ls::Timer::isDone(), ls::PurePursuit::isFinished(), left, ls::PursuitOutput::linear, odom, right, ls::PurePursuit::setPath(), and ls::PurePursuit::update().
getAngularControl()
std::shared_ptr< AbstractPID > ls::Chassis::getAngularControl ()
Get the angular motion PID controller.
Returns
Shared pointer to the angular PID controller
Definition at line 88 of file chassis.cpp.
References angular_control.
getController()
pros::Controller * ls::Chassis::getController () inline
Get the currently associated controller.
Returns
Pointer to the PROS controller (nullptr if not set)
Definition at line 114 of file chassis.h.
References controller.
getLateralControl()
std::shared_ptr< AbstractPID > ls::Chassis::getLateralControl ()
Get the lateral motion PID controller.
Returns
Shared pointer to the lateral PID controller
Definition at line 84 of file chassis.cpp.
References lateral_control.
getLeftMotors()
std::shared_ptr< pros::MotorGroup > ls::Chassis::getLeftMotors ()
Get the left motor group.
Returns
Shared pointer to the left motor group
Definition at line 100 of file chassis.cpp.
References left.
getLeftMotorVec()
std::vector< pros::Motor > & ls::Chassis::getLeftMotorVec ()
Get the left motor vector.
Returns
Vector of left motors
Definition at line 92 of file chassis.cpp.
References left_motors.
getOdom()
std::shared_ptr< ls::AbstractOdom > ls::Chassis::getOdom ()
Get access to the odometry system.
Provides access to the chassis's odometry system for position tracking and pose estimation.
Returns
Shared pointer to the odometry system
Definition at line 80 of file chassis.cpp.
References odom.
getRightMotors()
std::shared_ptr< pros::MotorGroup > ls::Chassis::getRightMotors ()
Get the right motor group.
Returns
Shared pointer to the right motor group
Definition at line 104 of file chassis.cpp.
References right.
getRightMotorVec()
std::vector< pros::Motor > & ls::Chassis::getRightMotorVec ()
Get the right motor vector.
Returns
Vector of right motors
Definition at line 96 of file chassis.cpp.
References right_motors.
isAdaptivePIDEnabled()
bool ls::Chassis::isAdaptivePIDEnabled () const
Check if adaptive PID is enabled.
Returns
true if adaptive PID is enabled, false otherwise
Definition at line 108 of file chassis.cpp.
References enable_adaptive_pid.
move_priority()
double ls::Chassis::move_priority (Angle & angle) const private
Calculate movement priority for coordinated motion.
Calculates a priority value from [0, 1] representing the percentage by which turn motion has priority over lateral motion. This is useful for smooth point-to-point movements that require both translation and rotation.
Parameters
angle Target angle for movement coordination
Returns
Priority value between 0.0 and 1.0
Definition at line 245 of file chassis.cpp.
References ls::Angle::convertToRadians(), and turn_sensitivity.
Referenced by moveToPoint().
moveToPoint()
void ls::Chassis::moveToPoint (double X, double Y, unsigned int timeout, bool reverse = false)
Move chassis to a specific point in Cartesian coordinates.
Moves the robot to the specified (X, Y) position using odometry feedback and PID control. The origin (0, 0) is the latest odometry reset point.
Parameters
X Target X coordinate in inches
Y Target Y coordinate in inches
timeout Maximum time to complete movement in milliseconds
reverse Whether to drive in reverse (default: false)
Note
This function is currently marked as TODO and may not be fully implemented
Definition at line 112 of file chassis.cpp.
References ls::Position::angleToPosition(), angular_control, cancel_button, ls::clampPower(), controller, DBG_PRINT, ls::distance(), ls::Position::distanceFromPointSigned(), enable_cancel, ls::Angle::getAngle(), ls::Timer::isDone(), lateral_control, left, LOOP_DELAY, ls::Angle::minimumAngleDifference(), move_priority(), ls::Angle::normalize(), odom, right, ls::Position::theta, threshold_lateral, and threshold_timeout.
operator=() [1/2]
Chassis & ls::Chassis::operator= (Chassis &&) default
References Chassis(), and ls::distance().
operator=() [2/2]
Chassis & ls::Chassis::operator= (const Chassis &) default
References Chassis().
setController()
void ls::Chassis::setController (pros::Controller & cont)
Set the controller for user input and cancellation.
Associates a PROS controller with the chassis for manual control and autonomous movement cancellation.
Parameters
cont Reference to PROS controller object
Definition at line 65 of file chassis.cpp.
References controller.
tank_drive()
void ls::Chassis::tank_drive (double left_y, double right_y)
Manual tank drive control.
Controls the chassis using tank drive logic where left and right sides are controlled independently. Values should be in range [-1, 1] or [-127, 127] depending on motor configuration.
Parameters
left_y Left side motor power/input
right_y Right side motor power/input
turnRelative()
double ls::Chassis::turnRelative (double deltaAngle, unsigned int timeout)
Turn by a relative angle change.
Rotates the robot by the specified angle delta from its current heading. Positive angles turn clockwise, negative turn counterclockwise.
Parameters
deltaAngle Angle change in degrees (positive = clockwise)
timeout Maximum time to complete turn in milliseconds
Returns
Actual angle change achieved when movement completed or timed out
Definition at line 325 of file chassis.cpp.
References DBG_PRINT, odom, and turnToAngle().
turnToAngle()
double ls::Chassis::turnToAngle (double angle, unsigned int timeout)
Turn chassis to a specific absolute angle.
Rotates the robot to face the specified absolute bearing angle using PID control and odometry feedback.
Parameters
angle Target angle in degrees (0° = North, 90° = East)
timeout Maximum time to complete turn in milliseconds
Returns
Actual angle achieved when movement completed or timed out
Definition at line 335 of file chassis.cpp.
References angular_control, cancel_button, ls::clampPower(), controller, DBG_PRINT, enable_cancel, ls::Angle::getAngle(), ls::Timer::isDone(), left, LOOP_DELAY, ls::Angle::minimumAngleDifference(), odom, right, threshold_angular, and threshold_timeout.
Referenced by turnRelative().
turnToPoint()
void ls::Chassis::turnToPoint (double X, double Y, unsigned int timeout, bool reverse = false)
Turn chassis to face a specific point.
Rotates the robot to face the specified (X, Y) point while maintaining current position. Uses odometry for position feedback.
Parameters
X Target X coordinate to face
Y Target Y coordinate to face
timeout Maximum time to complete turn in milliseconds
reverse Whether to face the point in reverse (180° offset)
Note
This function is currently marked as TODO and may not be fully implemented
Definition at line 181 of file chassis.cpp.
References ls::Position::angleToPosition(), angular_control, cancel_button, ls::clampPower(), controller, DBG_PRINT, enable_cancel, ls::Angle::getAngle(), ls::Timer::isDone(), left, LOOP_DELAY, ls::Angle::minimumAngleDifference(), ls::Angle::normalize(), odom, right, ls::Position::theta, threshold_angular, and threshold_timeout.
updateAdaptivePID()
void ls::Chassis::updateAdaptivePID ()
Update adaptive PID controllers.
Should be called periodically during autonomous operation to allow adaptive PID controllers to adjust parameters based on system performance.
Definition at line 69 of file chassis.cpp.
References angular_adaptive_controller, enable_adaptive_pid, and lateral_adaptive_controller.
Member Data Documentation
angular_adaptive_controller
std::unique_ptr<AdaptivePIDController> ls::Chassis::angular_adaptive_controller private
Adaptive angular PID
Definition at line 96 of file chassis.h.
Referenced by Chassis(), and updateAdaptivePID().
angular_control
std::shared_ptr<ls::AbstractPID> ls::Chassis::angular_control private
PID controller for turning motion
Definition at line 83 of file chassis.h.
Referenced by Chassis(), getAngularControl(), moveToPoint(), turnToAngle(), and turnToPoint().
cancel_button
pros::controller_digital_e_t ls::Chassis::cancel_button private
Controller button for cancellation
Definition at line 90 of file chassis.h.
Referenced by Chassis(), driveRelative(), moveToPoint(), turnToAngle(), and turnToPoint().
controller
pros::Controller* ls::Chassis::controller private
PROS controller for user input
Definition at line 92 of file chassis.h.
Referenced by Chassis(), driveRelative(), getController(), moveToPoint(), setController(), turnToAngle(), and turnToPoint().
enable_adaptive_pid
bool ls::Chassis::enable_adaptive_pid private
Adaptive PID enable flag
Definition at line 91 of file chassis.h.
Referenced by Chassis(), isAdaptivePIDEnabled(), and updateAdaptivePID().
enable_cancel
bool ls::Chassis::enable_cancel private
Controller cancellation enable flag
Definition at line 89 of file chassis.h.
Referenced by Chassis(), driveRelative(), moveToPoint(), turnToAngle(), and turnToPoint().
lateral_adaptive_controller
std::unique_ptr<AdaptivePIDController> ls::Chassis::lateral_adaptive_controller private
Adaptive lateral PID
Definition at line 95 of file chassis.h.
Referenced by Chassis(), and updateAdaptivePID().
lateral_control
std::shared_ptr<ls::AbstractPID> ls::Chassis::lateral_control private
PID controller for forward/backward motion
Definition at line 82 of file chassis.h.
Referenced by Chassis(), driveRelative(), getLateralControl(), and moveToPoint().
left
std::shared_ptr<pros::MotorGroup> ls::Chassis::left private
Left side motor group
Definition at line 79 of file chassis.h.
Referenced by Chassis(), driveRelative(), followPath(), getLeftMotors(), moveToPoint(), turnToAngle(), and turnToPoint().
left_motors
std::vector<pros::Motor> ls::Chassis::left_motors private
Left side motors
Definition at line 76 of file chassis.h.
Referenced by Chassis(), and getLeftMotorVec().
odom
std::shared_ptr<ls::AbstractOdom> ls::Chassis::odom private
Odometry system for position tracking
Definition at line 80 of file chassis.h.
Referenced by Chassis(), driveRelative(), followPath(), getOdom(), moveToPoint(), turnRelative(), turnToAngle(), and turnToPoint().
right
std::shared_ptr<pros::MotorGroup> ls::Chassis::right private
Right side motor group
Definition at line 78 of file chassis.h.
Referenced by Chassis(), driveRelative(), followPath(), getRightMotors(), moveToPoint(), turnToAngle(), and turnToPoint().
right_motors
std::vector<pros::Motor> ls::Chassis::right_motors private
Right side motors
Definition at line 77 of file chassis.h.
Referenced by Chassis(), and getRightMotorVec().
threshold_angular
double ls::Chassis::threshold_angular private
Angular movement completion threshold
Definition at line 87 of file chassis.h.
Referenced by Chassis(), turnToAngle(), and turnToPoint().
threshold_lateral
double ls::Chassis::threshold_lateral private
Lateral movement completion threshold
Definition at line 86 of file chassis.h.
Referenced by Chassis(), driveRelative(), and moveToPoint().
threshold_timeout
unsigned int ls::Chassis::threshold_timeout private
Dwell time after threshold met
Definition at line 88 of file chassis.h.
Referenced by Chassis(), driveRelative(), moveToPoint(), turnToAngle(), and turnToPoint().
turn_sensitivity
double ls::Chassis::turn_sensitivity private
Turn input sensitivity multiplier
Definition at line 85 of file chassis.h.
Referenced by Chassis(), and move_priority().
The documentation for this class was generated from the following files:
include/LibStoga/chassis.h
src/LibStoga/chassis.cpp