LibStoga: ls::MCLTracker Class Reference
ls::MCLTracker Class Reference
Monte Carlo Localization tracker using particle filtering.
#include <mcl.h>
Classes
struct Config
Configuration parameters for MCL system.
Public Member Functions
MCLTracker (const Config &cfg)
Construct MCL tracker with configuration.
void initialize (std::initializer_list< uint8_t >) override
Initialize the MCL system (not used directly)
void compute () override
Update particle positions and compute robot pose.
double getDeltaX () override
Get X position change since last compute.
double getDeltaY () override
Get Y position change since last compute.
Angle getDeltaAngle () override
Get heading change since last compute.
void injectMeasurement (double x, double y, double headingDeg, double stdXY=2.0, double stdHeading=5.0)
Inject absolute position measurement.
Public Member Functions inherited from ls::AbstractOdom
virtual double getX ()
Get current X coordinate.
virtual double getY ()
Get current Y coordinate.
virtual double getAngle ()
Get current heading angle.
virtual Position getPosition ()
Get complete current position.
virtual void resetX ()
Reset X coordinate to zero.
virtual void resetY ()
Reset Y coordinate to zero.
virtual void resetAngle ()
Reset heading angle to zero.
virtual void resetAll ()
Reset all position and heading to zero.
virtual ~AbstractOdom ()=default
Virtual destructor for proper cleanup.
Private Member Functions
void initParticles ()
Initialize particles randomly across the field.
void motionUpdate ()
Update particle positions based on motion model.
void normalize ()
Normalize particle weights to sum to 1.0.
void resample ()
Resample particles based on their weights.
void updateEstimate ()
Update robot pose estimate from particle distribution.
Private Attributes
Config config
std::vector< Particle > particles
std::default_random_engine rng {12345}
double deltaX = 0
double deltaY = 0
double deltaTheta = 0
Additional Inherited Members
Protected Member Functions inherited from ls::AbstractOdom
AbstractOdom ()
Protected constructor for derived classes.
Protected Attributes inherited from ls::AbstractOdom
Position pos
Position prev_pos
Detailed Description
Monte Carlo Localization tracker using particle filtering.
Implements advanced robot localization using a particle filter approach. This system maintains multiple hypotheses about the robot's position and uses sensor measurements to determine the most likely pose.
The MCL system is particularly effective in environments where:
Wheel odometry is unreliable (slippery surfaces, uneven terrain)
The robot may be moved by external forces (kidnapped robot)
Absolute position measurements are available (vision, GPS, etc.)
Usage Example:
// Configure MCL with 300 particles for 12x12ft field
MCLTracker::Config config{
    .count = 300,
    .processNoiseXY = 0.3,
    .processNoiseTheta = 1.5,
    .fieldW = 144.0,
    .fieldH = 144.0
};
MCLTracker tracker(config);
// In main loop
tracker.compute(); // Update particle positions
// Inject absolute measurements when available
tracker.injectMeasurement(24.0, 36.0, 45.0, 1.0, 3.0);
// Get current position estimate
double x = tracker.getX();
double y = tracker.getY();
Definition at line 92 of file mcl.h.
Constructor & Destructor Documentation
MCLTracker()
ls::MCLTracker::MCLTracker (const Config & cfg) explicit
Construct MCL tracker with configuration.
Creates a Monte Carlo Localization system with the specified configuration. The system will initialize particles randomly across the field.
Parameters
cfg Configuration parameters for the MCL system
Member Function Documentation
compute()
void ls::MCLTracker::compute () override virtual
Update particle positions and compute robot pose.
Performs the complete MCL update cycle:
Motion update based on odometry
Weight normalization
Resampling based on particle weights
Update position estimate from particle distribution
Reimplemented from ls::AbstractOdom.
Definition at line 56 of file mcl.cpp.
References motionUpdate(), normalize(), resample(), and updateEstimate().
getDeltaAngle()
Angle ls::MCLTracker::getDeltaAngle () inline override virtual
Get heading change since last compute.
Returns
Delta angle in degrees since last update
Implements ls::AbstractOdom.
Definition at line 158 of file mcl.h.
References deltaTheta.
getDeltaX()
double ls::MCLTracker::getDeltaX () inline override virtual
Get X position change since last compute.
Returns
Delta X in inches since last update
Implements ls::AbstractOdom.
Definition at line 144 of file mcl.h.
References deltaX.
getDeltaY()
double ls::MCLTracker::getDeltaY () inline override virtual
Get Y position change since last compute.
Returns
Delta Y in inches since last update
Implements ls::AbstractOdom.
Definition at line 151 of file mcl.h.
References deltaY.
initialize()
void ls::MCLTracker::initialize (std::initializer_list< uint8_t >) inline override virtual
Initialize the MCL system (not used directly)
This method is required by the AbstractOdom interface but is not used in MCL since initialization is handled in the constructor.
Parameters
ports Not used in MCL implementation
Implements ls::AbstractOdom.
Definition at line 126 of file mcl.h.
initParticles()
void ls::MCLTracker::initParticles () private
Initialize particles randomly across the field.
Creates the initial particle population with uniform distribution across the configured field dimensions.
Definition at line 7 of file mcl.cpp.
References config, particles, and rng.
injectMeasurement()
void ls::MCLTracker::injectMeasurement (double x, double y, double headingDeg, double stdXY = 2.0, double stdHeading = 5.0)
Inject absolute position measurement.
Updates particle weights based on an absolute position measurement from external sensors (vision system, GPS, etc.). This helps correct for odometry drift and improves localization accuracy.
Parameters
x Measured X coordinate in inches
y Measured Y coordinate in inches
headingDeg Measured heading in degrees (bearing system)
stdXY Standard deviation of position measurement (inches)
stdHeading Standard deviation of heading measurement (degrees)
Definition at line 63 of file mcl.cpp.
References ls::angleDiff(), normalize(), and particles.
motionUpdate()
void ls::MCLTracker::motionUpdate () private
Update particle positions based on motion model.
Propagates each particle forward based on the robot's movement as reported by odometry, adding appropriate process noise.
Definition at line 15 of file mcl.cpp.
References config, particles, and rng.
Referenced by compute().
normalize()
void ls::MCLTracker::normalize () private
Normalize particle weights to sum to 1.0.
Ensures particle weights form a valid probability distribution by scaling them so they sum to 1.0.
Definition at line 28 of file mcl.cpp.
References particles.
Referenced by compute(), and injectMeasurement().
resample()
void ls::MCLTracker::resample () private
Resample particles based on their weights.
Creates a new particle set by sampling from the current particles with probability proportional to their weights. This concentrates particles in high-probability regions.
Definition at line 33 of file mcl.cpp.
References particles, and rng.
Referenced by compute().
updateEstimate()
void ls::MCLTracker::updateEstimate () private
Update robot pose estimate from particle distribution.
Calculates the robot's position and heading as the weighted average of all particles, providing the best estimate of the current pose.
Definition at line 48 of file mcl.cpp.
References ls::angleDiff(), deltaTheta, deltaX, deltaY, particles, and ls::AbstractOdom::pos.
Referenced by compute().
Member Data Documentation
config
Config ls::MCLTracker::config private
MCL configuration parameters
Definition at line 177 of file mcl.h.
Referenced by initParticles(), and motionUpdate().
deltaTheta
double ls::MCLTracker::deltaTheta = 0 private
Heading change since last compute
Definition at line 182 of file mcl.h.
Referenced by getDeltaAngle(), and updateEstimate().
deltaX
double ls::MCLTracker::deltaX = 0 private
X position change since last compute
Definition at line 180 of file mcl.h.
Referenced by getDeltaX(), and updateEstimate().
deltaY
double ls::MCLTracker::deltaY = 0 private
Y position change since last compute
Definition at line 181 of file mcl.h.
Referenced by getDeltaY(), and updateEstimate().
particles
std::vector<Particle> ls::MCLTracker::particles private
Particle population
Definition at line 178 of file mcl.h.
Referenced by initParticles(), injectMeasurement(), motionUpdate(), normalize(), resample(), and updateEstimate().
rng
std::default_random_engine ls::MCLTracker::rng {12345} private
Random number generator
Definition at line 179 of file mcl.h.
Referenced by initParticles(), motionUpdate(), and resample().
The documentation for this class was generated from the following files:
include/LibStoga/mcl.h
src/LibStoga/mcl.cpp