LibStoga: ls Namespace Reference
ls Namespace Reference
Contains all source code for abstract classes or composed ones Basically code that powers abstraction.
Classes
class AbstractOdom
Abstract base class for all odometry implementations.
class AbstractPID
Abstract base class for PID controllers.
class AdaptivePIDController
Adaptive PID controller with real-time gain adjustment.
class Angle
A class to represent and manipulate angles in robotics applications.
class Chassis
Main chassis control class for robot movement.
class ChassisBuilder
Builder pattern for chassis configuration and construction.
struct ChassisConfig
Configuration structure for Chassis behavior.
struct ChassisControllerConfig
Chassis controller configuration.
struct ChassisTolerances
Movement completion thresholds and timing parameters.
class DataLogger
Comprehensive SD card data logging and persistence system.
class DriverControl
Enhanced driver control system with multiple drive modes.
struct DrivetrainConfig
Drivetrain mechanical and electrical configuration.
class EnhancedChassis
Enhanced chassis control interface with advanced movement capabilities.
struct FollowPathParams
Parameters for path following movements.
struct imu_odom_parameters_t
Configuration parameters for IMU-based odometry.
class ImuOdom
IMU-enhanced two-wheel odometry implementation.
class JoystickCurve
Joystick curve utilities for enhanced driver control.
class MCLTracker
Monte Carlo Localization tracker using particle filtering.
struct MoveToPointParams
Parameters for point-to-point movement.
struct MoveToPoseParams
Parameters for pose (position + heading) movement.
struct OdomConfig
Odometry system configuration.
struct Particle
Individual particle representing a possible robot pose.
class PID
Standard PID controller implementation.
struct PIDGains
Complete PID controller gain configuration.
struct Point
2D point representation in Cartesian coordinates
struct Pose
2D pose representation with position and orientation
struct Position
Complete robot pose representation (position + orientation)
class PurePursuit
Pure Pursuit path following controller.
struct PursuitOutput
Output structure for Pure Pursuit calculations.
struct smart_pid_parameters_t
Configuration parameters for Smart PID controller.
class SmartPID
Smart PID controller with adaptive learning capabilities.
struct SwingToHeadingParams
Parameters for swing turn movements.
struct SwingToPointParams
Parameters for swing turns to face a point.
class SystemHealthMonitor
Comprehensive system health monitoring and diagnostics.
struct threewheel_odom_parameters_t
Configuration parameters for three-wheel odometry.
class ThreeWheelOdom
Three-wheel odometry implementation.
class Timer
High-precision timer with pause/resume functionality.
struct tracking_rotation_parameters_t
Configuration parameters for tracking wheel sensors.
class TrackingWheel
Tracking wheel sensor wrapper for odometry calculations.
struct TurnToHeadingParams
Parameters for heading rotation movements.
Typedefs
using Path = std::vector<Point>
Type alias for a sequence of waypoints.
Enumerations
enum class AngularDirection { AUTO , CW_CLOCKWISE , CCW_COUNTERCLOCKWISE }
Angular rotation direction options.
Functions
void autoTune (std::shared_ptr< Chassis > chassis)
Automatically tune PID controllers using star pattern test.
void updateAdaptivePID ()
Update all adaptive PID controllers.
void recordMovementPerformance (double lateral_error, double lateral_settling_time, double angular_error, double angular_settling_time)
Record movement performance data for adaptive learning.
PIDGains getCurrentLateralGains ()
Get current adapted lateral PID gains.
PIDGains getCurrentAngularGains ()
Get current adapted angular PID gains.
DataLogger & getDataLogger ()
Get global data logger instance.
void __throw_error (const char *error, unsigned long line, const char *file)
Internal function for error handling and display.
double degreesToRadians (double degrees)
Convert degrees to radians.
double radiansToDegrees (double radians)
Convert radians to degrees.
double distance (const Point &a, const Point &b)
Calculate Euclidean distance between two points.
Angle bearingTo (const Point &a, const Point &b)
Calculate bearing angle from point A to point B.
double angleDiff (double a, double b)
Calculate the smallest angle difference between two angles.
SystemHealthMonitor & getHealthMonitor ()
Get global system health monitor instance.
template<typename T>
T clamp (const T &v, const T &lo, const T &hi)
Generic value clamping function.
double clampPower (double v)
Clamp motor power to VEX V5 range.
double deadband (double v, double db)
Apply deadband to reduce noise.
double scale (double v, double inMin, double inMax, double outMin, double outMax, bool clampResult=true)
Linear scaling between ranges.
template<typename T>
int sign (T v)
Extract sign of value.
std::ostream & operator<< (std::ostream &os, const Angle &a)
Stream operator for Angle type.
std::ostream & operator<< (std::ostream &os, const Position &p)
Stream operator for Position type.
static std::pair< double, double > findUltimateGainsRelay (std::shared_ptr< Chassis > chassis, bool isAngular)
static void adaptiveTune (std::shared_ptr< Chassis > chassis, PIDGains &lateral_gains, PIDGains &angular_gains, pros::Controller *controller)
int sgn (float val)
Variables
static std::unique_ptr< AdaptivePIDController > lateral_adaptive_controller
static std::unique_ptr< AdaptivePIDController > angular_adaptive_controller
Detailed Description
Contains all source code for abstract classes or composed ones Basically code that powers abstraction.
Code for ImuOdom class.
Code for ThreeWheelOdom class.
Typedef Documentation
Path
using ls::Path = std::vector<Point>
Type alias for a sequence of waypoints.
Represents a path as a series of points that can be followed by motion planning algorithms like pure pursuit.
Definition at line 159 of file geometry.h.
Enumeration Type Documentation
AngularDirection
enum class ls::AngularDirection strong
Angular rotation direction options.
Specifies the direction for rotational movements, allowing control over whether turns should be clockwise, counter-clockwise, or automatically choose the shortest path.
Enumerator
AUTO
Automatically choose shortest rotation direction
CW_CLOCKWISE
Force clockwise rotation
CCW_COUNTERCLOCKWISE
Force counter-clockwise rotation
Definition at line 51 of file enhanced_chassis.h.
Function Documentation
__throw_error()
void ls::__throw_error (const char * error, unsigned long line, const char * file) inline
Internal function for error handling and display.
This function handles the actual error display and program halting. It displays the error information on the PROS LCD screen and enters an infinite loop to halt program execution.
The function clears the first two lines of the LCD and displays:
Line 0: File and line number information
Line 1: The error message
Parameters
error The error message to display
line The line number where the error occurred
file The source file where the error occurred
Note
This function never returns - it halts execution indefinitely
Warning
Only call this function through the THROW_ERROR macro
Definition at line 79 of file error.h.
adaptiveTune()
void ls::adaptiveTune (std::shared_ptr< Chassis > chassis, PIDGains & lateral_gains, PIDGains & angular_gains, pros::Controller * controller) static
Definition at line 245 of file auton_tuner.cpp.
References ls::PIDGains::kD, ls::PIDGains::kI, and ls::PIDGains::kP.
Referenced by autoTune().
angleDiff()
double ls::angleDiff (double a, double b)
Calculate the smallest angle difference between two angles.
Returns the minimum angle difference considering the circular nature of angles. Result is in range [-180, 180].
Parameters
a First angle in degrees
b Second angle in degrees
Returns
Minimum angle difference in degrees
Definition at line 74 of file geometry.cpp.
Referenced by ls::MCLTracker::injectMeasurement(), and ls::MCLTracker::updateEstimate().
autoTune()
void ls::autoTune (std::shared_ptr< Chassis > chassis)
Automatically tune PID controllers using star pattern test.
Performs automatic PID tuning by commanding the robot to move in a star pattern (multiple directions and distances). The system analyzes the performance of each movement and optimizes PID gains accordingly.
Tuning Process:
Moves robot in 8 different directions (45-degree increments)
Tests various distances to assess different speed ranges
Analyzes overshoot, settling time, and steady-state error
Iteratively adjusts gains using optimization algorithms
Validates final gains with additional test movements
Parameters
chassis Shared pointer to chassis object to tune
Note
This is a blocking operation that may take several minutes
Warning
Robot should be in a clear area with space to move freely
Definition at line 432 of file auton_tuner.cpp.
References adaptiveTune(), findUltimateGainsRelay(), ls::PIDGains::kD, ls::PIDGains::kI, and ls::PIDGains::kP.
bearingTo()
Angle ls::bearingTo (const Point & a, const Point & b)
Calculate bearing angle from point A to point B.
Returns the bearing angle (in degrees) from point A to point B, where 0° = North, 90° = East, etc.
Parameters
a Starting point
b Target point
Returns
Bearing angle in degrees [0, 360)
Definition at line 66 of file geometry.cpp.
References radiansToDegrees(), ls::Point::x, and ls::Point::y.
clamp()
template<typename T> T ls::clamp (const T & v, const T & lo, const T & hi) inline
Generic value clamping function.
Constrains a value to fall within a specified range. This is a convenience wrapper around std::clamp that maintains namespace consistency.
Template Parameters
T Value type (must support comparison operators)
Parameters
v Value to clamp
lo Lower bound (inclusive)
hi Upper bound (inclusive)
Returns
Value constrained to [lo, hi] range
Note
If v < lo, returns lo. If v > hi, returns hi. Otherwise returns v.
Definition at line 77 of file clamp.hpp.
Referenced by clampPower(), and scale().
clampPower()
double ls::clampPower (double v) inline
Clamp motor power to VEX V5 range.
Constrains motor power values to the valid range for VEX V5 motors. This prevents motor damage from over-powering and ensures compatibility with PROS motor control functions.
Parameters
v Raw motor power value
Returns
Power value clamped to [-127, 127] range
Note
VEX V5 motors accept power values from -127 (full reverse) to 127 (full forward)
Definition at line 93 of file clamp.hpp.
References clamp().
Referenced by ls::Chassis::driveRelative(), ls::Chassis::followPath(), ls::Chassis::moveToPoint(), ls::Chassis::turnToAngle(), and ls::Chassis::turnToPoint().
deadband()
double ls::deadband (double v, double db) inline
Apply deadband to reduce noise.
Zeroes out small magnitude values to reduce noise and prevent unwanted small movements. Values within the deadband range are treated as zero, while larger values are passed through unchanged.
Parameters
v Input value
db Deadband threshold (must be >= 0)
Returns
Input value with deadband applied
Note
Commonly used with joystick inputs and sensor readings
db = 0 disables deadband (no effect)
Definition at line 109 of file clamp.hpp.
degreesToRadians()
double ls::degreesToRadians (double degrees)
Convert degrees to radians.
Parameters
degrees Angle in degrees
Returns
Equivalent angle in radians
Definition at line 50 of file geometry.cpp.
Referenced by ls::Angle::convertToRadians(), ls::ThreeWheelOdom::getDeltaX(), ls::ThreeWheelOdom::getDeltaY(), and ls::PurePursuit::update().
distance()
double ls::distance (const Point & a, const Point & b)
Calculate Euclidean distance between two points.
Parameters
a First point
b Second point
Returns
Distance between points (always positive)
Definition at line 60 of file geometry.cpp.
References ls::Point::x, and ls::Point::y.
Referenced by ls::Chassis::driveRelative(), ls::PurePursuit::findLookahead(), ls::Chassis::moveToPoint(), ls::Chassis::operator=(), ls::PurePursuit::update(), and ls::EnhancedChassis::waitUntil().
findUltimateGainsRelay()
std::pair< double, double > ls::findUltimateGainsRelay (std::shared_ptr< Chassis > chassis, bool isAngular) static
Definition at line 178 of file auton_tuner.cpp.
References ls::Timer::isDone().
Referenced by autoTune().
getCurrentAngularGains()
PIDGains ls::getCurrentAngularGains ()
Get current adapted angular PID gains.
Returns the current PID gains for angular (turning) movement after applying all adaptive compensations.
Returns
Current angular PID gains with adaptations applied
Definition at line 501 of file auton_tuner.cpp.
References angular_adaptive_controller.
getCurrentLateralGains()
PIDGains ls::getCurrentLateralGains ()
Get current adapted lateral PID gains.
Returns the current PID gains for lateral (forward/backward) movement after applying all adaptive compensations.
Returns
Current lateral PID gains with adaptations applied
Definition at line 495 of file auton_tuner.cpp.
References lateral_adaptive_controller.
getDataLogger()
DataLogger & ls::getDataLogger () inline
Get global data logger instance.
Returns a reference to the global DataLogger instance, providing a singleton pattern for easy access throughout the codebase.
Returns
Reference to global data logger
Definition at line 235 of file data_logger.h.
getHealthMonitor()
SystemHealthMonitor & ls::getHealthMonitor () inline
Get global system health monitor instance.
Returns a reference to the global SystemHealthMonitor instance. This provides a singleton pattern for easy access throughout the codebase.
Returns
Reference to global health monitor
Definition at line 279 of file system_health.h.
operator<<() [1/2]
std::ostream & ls::operator<< (std::ostream & os, const Angle & a) inline
Stream operator for Angle type.
Outputs an Angle object to a stream in a human-readable format. Displays the angle value in degrees followed by "deg" suffix.
Parameters
os Output stream
a Angle object to output
Returns
Reference to the output stream
Note
Output format: "45.2deg"
Definition at line 87 of file logging.hpp.
References ls::Angle::getAngle().
operator<<() [2/2]
std::ostream & ls::operator<< (std::ostream & os, const Position & p) inline
Stream operator for Position type.
Stream output operator for debugging.
Outputs a Position object to a stream showing X, Y coordinates and heading angle in a structured format.
Parameters
os Output stream
p Position object to output
Returns
Reference to the output stream
Note
Output format: "{X=24.5, Y=12.3, theta=45.2deg}"
Definition at line 103 of file logging.hpp.
References ls::Angle::getAngle(), ls::Position::theta, ls::Position::X, and ls::Position::Y.
radiansToDegrees()
double ls::radiansToDegrees (double radians)
Convert radians to degrees.
Parameters
radians Angle in radians
Returns
Equivalent angle in degrees
Definition at line 55 of file geometry.cpp.
Referenced by bearingTo().
recordMovementPerformance()
void ls::recordMovementPerformance (double lateral_error, double lateral_settling_time, double angular_error, double angular_settling_time)
Record movement performance data for adaptive learning.
Records performance metrics from completed movements to enable continuous learning and adaptation. This data helps improve PID performance over time and across different conditions.
Parameters
lateral_error Final position error for lateral movement (inches)
lateral_settling_time Time taken to settle laterally (milliseconds)
angular_error Final angle error for angular movement (degrees)
angular_settling_time Time taken to settle angularly (milliseconds)
Definition at line 484 of file auton_tuner.cpp.
References angular_adaptive_controller, and lateral_adaptive_controller.
scale()
double ls::scale (double v, double inMin, double inMax, double outMin, double outMax, bool clampResult = true) inline
Linear scaling between ranges.
Scales a value from one range to another using linear interpolation. Optionally clamps the result to the output range bounds.
Parameters
v Input value to scale
inMin Input range minimum
inMax Input range maximum
outMin Output range minimum
outMax Output range maximum
clampResult Whether to clamp result to output range
Returns
Scaled value in output range
Note
If inMax == inMin, returns outMin to avoid division by zero
Warning
Ensure inMin != inMax to avoid undefined behavior
Definition at line 128 of file clamp.hpp.
References clamp().
sgn()
int ls::sgn (float val) inline
Definition at line 28 of file pid.cpp.
Referenced by ls::PID::update().
sign()
template<typename T> int ls::sign (T v) inline
Extract sign of value.
Returns the sign of a value as an integer: -1 for negative, 0 for zero, and 1 for positive. Useful for directional logic and sign-preserving operations.
Template Parameters
T Value type (must support comparison operators)
Parameters
v Input value
Returns
Sign as integer: -1 (negative), 0 (zero), or 1 (positive)
Note
Equivalent to: (v > 0) - (v < 0)
Definition at line 150 of file clamp.hpp.
updateAdaptivePID()
void ls::updateAdaptivePID ()
Update all adaptive PID controllers.
Updates both lateral and angular adaptive PID controllers with current conditions and performance data. Should be called periodically during autonomous or driver control operation (every 50-100ms).
This function:
Updates battery voltage compensation
Performs surface condition detection
Applies adaptive gain adjustments
Maintains performance tracking windows
Definition at line 474 of file auton_tuner.cpp.
References angular_adaptive_controller, and lateral_adaptive_controller.
Variable Documentation
angular_adaptive_controller
std::unique_ptr<AdaptivePIDController> ls::angular_adaptive_controller static
Definition at line 175 of file auton_tuner.cpp.
Referenced by getCurrentAngularGains(), recordMovementPerformance(), and updateAdaptivePID().
lateral_adaptive_controller
std::unique_ptr<AdaptivePIDController> ls::lateral_adaptive_controller static
Definition at line 174 of file auton_tuner.cpp.
Referenced by getCurrentLateralGains(), recordMovementPerformance(), and updateAdaptivePID().