LibStoga: ls::Position Struct Reference
ls::Position Struct Reference
Complete robot pose representation (position + orientation)
#include <odom.h>
Public Member Functions
Position ()
Default constructor - initializes to origin with 0° heading.
Position (double x, double y, double t)
Construct position with specified coordinates and heading.
double distanceFromPoint (const Position &pos) const
Calculate Euclidean distance to another position.
double distanceFromPointSigned (const Position &pos) const
Calculate signed distance to another position.
int isBehind (const Position &pos) const
Determine relative position (front/behind robot)
Angle angleToPosition (const Position &pos) const
Calculate bearing angle to target position.
Public Attributes
double X
double Y
Angle theta
Friends
std::ostream & operator<< (std::ostream &os, const Position &pos)
Stream output operator for debugging.
Detailed Description
Complete robot pose representation (position + orientation)
Represents the full state of a robot in 2D space including X, Y coordinates and heading angle. This structure is fundamental to odometry and navigation systems throughout the framework.
The coordinate system uses:
Origin: Robot's starting position (0, 0)
Angles: Bearing system where 0° = North (forward direction)
Units: All distances in inches, angles in degrees
Definition at line 61 of file odom.h.
Constructor & Destructor Documentation
Position() [1/2]
ls::Position::Position () inline
Default constructor - initializes to origin with 0° heading.
Definition at line 69 of file odom.h.
References theta, X, and Y.
Referenced by angleToPosition(), distanceFromPoint(), distanceFromPointSigned(), isBehind(), and operator<<.
Position() [2/2]
ls::Position::Position (double x, double y, double t) inline
Construct position with specified coordinates and heading.
Parameters
x X coordinate in inches
y Y coordinate in inches
t Heading angle in degrees (bearing system)
Definition at line 78 of file odom.h.
References theta, X, and Y.
Member Function Documentation
angleToPosition()
Angle ls::Position::angleToPosition (const Position & pos) const
Calculate bearing angle to target position.
Computes the bearing angle from current position to target position. Returns angle in bearing system (0° = North).
Parameters
pos Target position
Returns
Bearing angle in degrees [0, 360), or infinity if positions are too close
Definition at line 91 of file odom.cpp.
References Position(), X, and Y.
Referenced by isBehind(), ls::Chassis::moveToPoint(), and ls::Chassis::turnToPoint().
distanceFromPoint()
double ls::Position::distanceFromPoint (const Position & pos) const
Calculate Euclidean distance to another position.
Computes the straight-line distance between this position and another. Always returns a positive value.
Parameters
pos Target position to measure distance to
Returns
Distance in inches (always positive)
Definition at line 60 of file odom.cpp.
References Position(), X, and Y.
Referenced by distanceFromPointSigned().
distanceFromPointSigned()
double ls::Position::distanceFromPointSigned (const Position & pos) const
Calculate signed distance to another position.
Returns signed distance based on robot's current heading. Positive values indicate points in front of the robot, negative values indicate points behind.
Parameters
pos Target position to measure distance to
Returns
Signed distance in inches (positive = forward, negative = backward)
Definition at line 67 of file odom.cpp.
References distanceFromPoint(), isBehind(), and Position().
Referenced by ls::Chassis::moveToPoint().
isBehind()
int ls::Position::isBehind (const Position & pos) const
Determine relative position (front/behind robot)
Analyzes whether a point is in front of, behind, or neither relative to the robot's current heading.
Parameters
pos Position to analyze
Returns
-1 if behind, 1 if in front, 0 if indeterminate (too close)
Definition at line 72 of file odom.cpp.
References angleToPosition(), ls::Angle::getAngle(), ls::Angle::normalize(), Position(), and theta.
Referenced by distanceFromPointSigned().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const Position & pos) friend
Stream output operator for debugging.
Formats position as "Pos(X, Y, theta)" for console output.
Parameters
os Output stream
pos Position to output
Returns
Modified output stream
Outputs a Position object to a stream showing X, Y coordinates and heading angle in a structured format.
Parameters
os Output stream
p Position object to output
Returns
Reference to the output stream
Note
Output format: "{X=24.5, Y=12.3, theta=45.2deg}"
Definition at line 133 of file odom.h.
References ls::Angle::getAngle(), Position(), theta, X, and Y.
Member Data Documentation
theta
Angle ls::Position::theta
Heading angle in degrees (bearing: 0° = North)
Definition at line 64 of file odom.h.
Referenced by isBehind(), ls::Chassis::moveToPoint(), ls::operator<<(), operator<<, Position(), Position(), and ls::Chassis::turnToPoint().
X
double ls::Position::X
X coordinate in inches from origin
Definition at line 62 of file odom.h.
Referenced by angleToPosition(), distanceFromPoint(), ls::operator<<(), operator<<, Position(), and Position().
Y
double ls::Position::Y
Y coordinate in inches from origin
Definition at line 63 of file odom.h.
Referenced by angleToPosition(), distanceFromPoint(), ls::operator<<(), operator<<, Position(), and Position().
The documentation for this struct was generated from the following files:
include/LibStoga/odom.h
src/LibStoga/odom.cpp